[book]
authors = ["PilgrimLyieu"]
language = "zh-CN"
multilingual = false
src = "src"
title = "NeoNotes"
description = "使用 mdBook 构建的课程笔记"

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "rust"

[output.html.fold]
enable = true
